SET search_path TO papita;

ALTER TABLE author
ALTER COLUMN id DROP DEFAULT;

ALTER TABLE post
ALTER COLUMN id DROP DEFAULT;

ALTER TABLE profile
ALTER COLUMN id DROP DEFAULT;

ALTER TABLE tag
ALTER COLUMN id DROP DEFAULT;
