SET search_path TO papita;

DROP TABLE IF EXISTS author CASCADE;
DROP TABLE IF EXISTS profile CASCADE;
DROP TABLE IF EXISTS tag CASCADE;
DROP TABLE IF EXISTS post CASCADE;
DROP TABLE IF EXISTS author_session CASCADE;
DROP TABLE IF EXISTS _post_tag CASCADE;

set TIMEZONE TO 'GMT';
